Repository dwyl/gitea-server, pull requests merged in 2022-05, with the labels that each got.

#2 Create fly application
  README.md
  fly.toml
Labels: awaiting-review

#5 Update Docs #1
  README.md
Labels: documentation, enhancement, awaiting-review, discuss, chore, priority-2, T25m

#7 Micro PR: to fix docs
  README.md
Labels: awaiting-review, chore
